myclass/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('', TemplateView.as_view(template_name='products/home.html'), name='home'),
]

products/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),   
    path('portfolio/', views.PortfolioView.as_view(),name='portfolio'),
    path('service/', views.ServiceView.as_view(),name="service"),
    path('blog/', views.BlogView.as_view(),name="blog"),
    path('about/', views.AboutView.as_view(),name="about"),
]

products/models.py
from django.db import models

# Create your models here.

products/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "products/home.html"

class PortfolioView(TemplateView):
    template_name = "products/portfolio.html"

class ServiceView(TemplateView):
    template_name = "products/service.html"

class BlogView(TemplateView):
    template_name = "products/blog.html"

class AboutView(TemplateView):
    template_name = "products/about.html"

products/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@100..900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'products/cssreset' %}">
    <link rel="stylesheet" href="{% static 'products/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'products/style.css' %}">

    <script src="{% static 'products/bootstrap.min.js' %}"></script>


    <title>作品集</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid ">
            <a class="navbar-brand logo" href="#">
                <img src="https://raw.githubusercontent.com/hexschool/2024-camp/50f102c3d67a1e39aa4028e5c5105411ce2c3394/src/assets/images/logo.svg"
                    alt="">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse titlelist" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'products:home' %}">首頁</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'products:portfolio' %}">作品集</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'products:service' %}">服務項目</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'products:blog' %}">部落格</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'products:about' %}">聯絡我</a>
                    </li>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock content %}

    <footer>
        <div class="container footer">
            <div class="connection">
                <div class="connection-logo"><img src="https://raw.githubusercontent.com/hexschool/2024-camp/50f102c3d67a1e39aa4028e5c5105411ce2c3394/src/assets/images/logo.svg" alt=""></div>
                <div class="connection-text">
                    <p>若有數位產品設計和開發相關問題 <br>
                        歡迎填寫表單，或直接與我聯絡！</p>                    
                    <p class="email"><a href="#">service@hexschool.com</a></p>
                </div>
            </div>
            <div class="switch">
                <div class="switch-item1"><a href="#"><img src="https://raw.githubusercontent.com/hexschool/2024-camp/50f102c3d67a1e39aa4028e5c5105411ce2c3394/src/assets/images/list.svg" alt="">填寫表單</a></div>
                <div class="switch-item"><a href="#"><img src="https://raw.githubusercontent.com/hexschool/2022-web-layout-training/2f8d8c7a6133b448ecff5bf0a3d282b87b7c6a7e/2024%20web-camp/instagram.svg" alt="">hexscool_demo</a></div>
                <div class="switch-item"><a href="#"><img src="https://raw.githubusercontent.com/hexschool/2022-web-layout-training/2f8d8c7a6133b448ecff5bf0a3d282b87b7c6a7e/2024%20web-camp/facebook.svg" alt="">hexschoolTW</a></div>
            </div>
        </div>
    </footer>


</body>
</html>

products/templates/products/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>im about!!</h1>




{% endblock content %}

products/templates/products/blog.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>im blog!!</h1>




{% endblock content %}

products/templates/products/home.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>im home!!</h1>




{% endblock content %}

products/templates/products/portfolio.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container banner">
    <div class="slogan">
        <h1>讓使用者在觀賞與使用的旅程中，發現<span class="focus-bg">設計的價值</span></h1>
        <h1>而我在設計與開發的過程中，看見<span class="focus-bg">自己的價值</span></h1>
    </div>
    <div class="introduce">
        <div class="text1">
            <h2>2B經驗</h2>
            <p>內部監控系統、庫存系統、 採購系統、 行銷整合系統</p>
        </div>
        <div class="text1">
            <h2>2C經驗</h2>
            <p>跨國美妝保養電商、 個人品牌網站、 醫美網站、 電子商務</p>
        </div>
    </div>
</div>
<div class="container">
    <div class="portfolio">
        <div class="item">
            <div class="photo">
                <img src="https://github.com/hexschool/2024-camp/blob/main/src/assets/images/work-image1.png?raw=true"
                    alt="">
            </div>
            <div class="text">
                <h3>星際旅行訂票平台</h3>
                <p>悠遊宇宙的夢想，從這裡開始實現</p>
                <ul>
                    <li><a href="">網頁設計</a></li>
                    <li><a href="">響應式設計</a></li>
                    <li><a href="">Bootstrap</a></li>
                </ul>
            </div>
        </div>
        <div class="item">
            <div class="photo">
                <img src="https://github.com/hexschool/2024-camp/blob/main/src/assets/images/work-image2.png?raw=true"
                    alt="">
            </div>
            <div class="text">
                <h3>理財App</h3>
                <p>連動帳戶與行動支付，讓 AI 提供您最好的理財建議</p>
                <ul>
                    <li><a href="">App設計</a></li>
                    <li><a href="">iOS</a></li>
                    <li><a href="">React</a></li>
                </ul>
            </div>
        </div>
        <div class="item">
            <div class="photo">
                <img src="https://github.com/hexschool/2024-camp/blob/main/src/assets/images/work-image3.png?raw=true"
                    alt="">
            </div>
            <div class="text">
                <h3>醫美診所官網</h3>
                <p>永保青春的秘密，從粹究開始</p>
                <ul>
                    <li><a href="">網頁設計</a></li>
                    <li><a href="">響應式設計</a></li>
                    <li><a href="">WordPress</a></li>
                </ul>
            </div>
        </div>
        <div class="item">
            <div class="photo">
                <img src="https://github.com/hexschool/2024-camp/blob/main/src/assets/images/work-image4.png?raw=true"
                    alt="">
            </div>
            <div class="text">
                <h3>美美美早餐店 POS 機 UI Design</h3>
                <p>訂單送單一目瞭然，自動報表分析好輕鬆</p>
                <ul>
                    <li><a href="">UI 設計</a></li>
                    <li><a href="">前端開發</a></li>
                    <li><a href="">Wix</a></li>
                </ul>
            </div>
        </div>
        <div class="item">
            <div class="photo">
                <img src="https://github.com/hexschool/2024-camp/blob/main/src/assets/images/work-image5.png?raw=true"
                    alt="">
            </div>
            <div class="text">
                <h3>電影院訂票系統</h3>
                <p>三步驟完成訂票，電腦手機都支援</p>
                <ul>
                    <li><a href="">前端開發</a></li>
                    <li><a href="">後端支援</a></li>
                    <li><a href="">Vue</a></li>
                </ul>
            </div>
        </div>
        <div class="item">
            <div class="photo">
                <img src="https://github.com/hexschool/2024-camp/blob/main/src/assets/images/work-image6.png?raw=true"
                    alt="">
            </div>
            <div class="text">
                <h3>巧克巧克形象官網設計</h3>
                <p>三步驟完成訂票，電腦手機都支援</p>
                <ul>
                    <li><a href="">UI設計</a></li>
                    <li><a href="">設計系統</a></li>
                    <li><a href="">網路電商</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container page">
    <div class="number"><a href="#">1</a></div>
    <div class="number"><a href="#">2</a></div>
    <div class="number"><a href="#">3</a></div>
</div>
{% endblock content %}

products/templates/products/service.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>im service</h1>




{% endblock content %}